const menu = [
  {
    id: 1,
    title: "Dosai",
    category: "breakfast",
    price: 12,
    img: "./images/dosai.webp",
    desc: `A dosa, also called dosai, dosey, or dosha, is a thin pancake in South Indian cuisine made from a fermented batter of ground black lentils and rice. Dosas are popular in South Asia as well as around the world. Dosas are served hot, often with chutney and sambar. `,
  },
  {
    id: 2,
    title: "South Indian Meals",
    category: "lunch",
    price: 18.99,
    img: "./images/SouthIndianMeals.jpg",
    desc: `South Indian Meals is a huge spread of rice, sambar, rasam, curd with porial, kootu, varuval, appalam, payasam, vadai & pickle. This is a tasty & filling menu for lunch at home during occasions, festivals and day to day cooking.`,
  },
  {
    id: 3,
    title: "Murukku",
    category: "shakes",
    price: 6.99,
    img: "./images/Murukku.jpg",
    desc: `Murukku is a savoury, crunchy snack originating from the Indian subcontinent. The name murukku derives from the Tamil word for "twisted", which refers to its shape. In India, murukku is especially common in the states of Andhra Pradesh, Tamil Nadu, Karnataka, and Kerala.`,
  },
  {
    id: 4,
    title: "Roast",
    category: "breakfast",
    price: 12.99,
    img: "./images/Roast.jpg",
    desc: `
    Masala dosa is a roasted dosa served with potato curry, chutney and sambar; while Saada (plain) dosa is prepared with lighter texture, paper dosa is a thin and crisp version.`,
  },
  {
    id: 5,
    title: "Mutton Biryani",
    category: "lunch",
    price: 20.99,
    img: "./images/muttonbiryani.jpg",
    desc: `Biryani is a mixed rice dish originating among the Muslims of the Indian subcontinent. It is made with Indian spices, rice, and usually some type of meat (chicken, beef, goat, lamb, prawn, fish) or in some cases without any meat, and sometimes, in addition, eggs and potatoes.`,
  },
  {
    id: 6,
    title: "Thattu Vadai",
    category: "shakes",
    price: 8.99,
    img: "./images/thaduVadai.jpg",
    desc: `Mix the rice flour and blackgram flour in a large bowl. Grind the red chilli and make it as powder. Add split Bengal gram, Roasted gram, Garlic cloves(crushed), Asafoetida, Red chilli powder and salt(to taste) with the flour. Now mix all together well by adding required water and turn it into a soft dough.`,
  },
  {
    id: 7,
    title: "Best Mix-BreakFast",
    category: "breakfast",
    price: 10.99,
    img: "./images/mix-breakfast.jpeg",
    desc: `A typical breakfast in India varies depending on region, but is often quite similar to a lunch or dinner. A breakfast plate in India might include roti (flatbread), dosas (thin crepes made of lentils) or idlis (steamed rice-dough pancakes), and different dips and chutneys, as well as spiced potatoes. `,
  },
  {
    id: 8,
    title: "Chicken Biryani",
    category: "lunch",
    price: 17.99,
    img: "./images/ChickenBriyani.jpg",
    desc: `Chicken Biryani is a savory chicken and rice dish that includes layers of chicken, rice, and aromatics that are steamed together. The bottom layer of rice absorbs all the chicken juices as it cooks, giving it a tender texture and rich flavor, while the top layer of rice turns out white and fluffy. `,
  },
  {
    id: 9,
    title: "JackFruit Biryani",
    category: "lunch",
    price: 16.99,
    img: "./images/jackfruit-biryani.jpg",
    desc: `As a matter of fact, with a surprisingly low-calorie content (A cup of raw jackfruit slices contains only 155 calories, with 8 grams of protein and 2.6 grams of fiber), jackfruit is a rich source of protein and fiber.`,
  },
  {
    id: 10,
    title: "Almond milk",
    category: "drinks",
    price: 6.99,
    img: "./images/badammilk.jpg",
    desc: `Almond milk is rich in vitamin E, which is an important antioxidant. Vitamin E can help lower your risk of serious health conditions like stroke, heart disease, and even cancer. Depending on the brand, enriched almond milk can also be an excellent source of: Phosphorus.`,
  },
  {
    id: 11,
    title: "Idli",
    category: "breakfast",
    price: 8.99,
    img: "./images/Idli.jpeg",
    desc: `Idli or idly is a type of savoury rice cake, originating from the South India,popular as breakfast foods in Southern India and in Sri Lanka. The cakes are made by steaming a batter consisting of fermented black lentils (de-husked) and rice.`,
  },
  {
    id: 12,
    title: "Achu Murukku",
    category: "shakes",
    price: 4.99,
    img: "./images/Achappam.jpg",
    desc: `Achappam batter is made from a blend of wheat flour or rice flour, eggs, sugar and coconut milk. Achappam can be eaten plain and is also commonly spiced with sesame, cumin, and cardamom.`,
  },
  {
    id: 13,
    title: "GroundNut Candy",
    category: "shakes",
    price: 10.99,
    img: "./images/groundneet.jpg",
    desc: `Peanut Chikki is a healthy, delicious traditional candy made from peanuts and jaggery. It can be eaten alone or with snacks and is a perfect replacement for chocolates. This recipe uses jaggery to make crispier chikkis in easier way.`,
  },
  {
    id: 14,
    title: "Neer Mor",
    category: "drinks",
    price: 6.99,
    img: "./images/neerMor.jpg",
    desc: `Neer mooru known as buttermilk in english is a common summer drink in South India. It is a simple concoction of water and yogurt mixed with salt and other Indian spices like mustard and cumin seeds and perfumed with herbs like curry leaves and cilantro.`,
  },
  {
    id: 15,
    title: "Rose Milk",
    category: "drinks",
    price: 6.99,
    img: "./images/RoseMilk.jpg",
    desc: `Rose milk has a slightly sweet floral flavor and tastes exactly what it sounds like – milky with a distinctive rose note.`,
  },
  {
    id: 16,
    title: "Tea-Vadai",
    category: "drinks",
    price: 8.99,
    img: "./images/vadaiAndTea.jpg",
    desc: `The benefits of tea include reducing the impact of stress, of protecting us from every chronic disease, from Alzheimer's Disease, Parkinson's Disease, its ability to strengthen the immune system, to fight cholesterol, and the naturally stimulating function of L-Theanine – are essential for a 21st century lifestyle.`,
  },
];
export default menu;
